spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:10201
server:
  port: 10101
eureka:
  client:
#    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:10002/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    metadata-map:
      versions: 1,2

graybunny:
  instance:
    grayEnroll: false
#  serverUrl: http://192.168.6.22:10202